/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppAlumnoRouteImport } from './routes/_app.alumno'
import { Route as AppAsociadoRouteImport } from './routes/_app.asociado'
import { Route as AppCreadorRouteImport } from './routes/_app.creador'
import { Route as AppSuperiorRouteImport } from './routes/_app.superior'
import { Route as AppAlumnoIndexRouteImport } from './routes/_app.alumno.index'
import { Route as AppAlumnoAprendeRouteImport } from './routes/_app.alumno.aprende'
import { Route as AppAlumnoEscanerRouteImport } from './routes/_app.alumno.escaner'
import { Route as AppAlumnoMapaRouteImport } from './routes/_app.alumno.mapa'
import { Route as AppAlumnoPremiosRouteImport } from './routes/_app.alumno.premios'
import { Route as AppAlumnoRankingRouteImport } from './routes/_app.alumno.ranking'
import { Route as AppAlumnoViajeRouteImport } from './routes/_app.alumno.viaje'
import { Route as AppAsociadoIndexRouteImport } from './routes/_app.asociado.index'
import { Route as AppAsociadoEscuelasRouteImport } from './routes/_app.asociado.escuelas'
import { Route as AppAsociadoLogisticaRouteImport } from './routes/_app.asociado.logistica'
import { Route as AppCreadorIndexRouteImport } from './routes/_app.creador.index'
import { Route as AppCreadorCircuitoRouteImport } from './routes/_app.creador.circuito'
import { Route as AppCreadorEducacionRouteImport } from './routes/_app.creador.educacion'
import { Route as AppCreadorPremiosRouteImport } from './routes/_app.creador.premios'
import { Route as AppCreadorRankingRouteImport } from './routes/_app.creador.ranking'
import { Route as AppSuperiorIndexRouteImport } from './routes/_app.superior.index'
import { Route as AppSuperiorConfigRouteImport } from './routes/_app.superior.config'
import { Route as AppSuperiorModulosRouteImport } from './routes/_app.superior.modulos'
import { Route as AppSuperiorUsuariosRouteImport } from './routes/_app.superior.usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAlumnoRoute = AppAlumnoRouteImport.update({
  id: '/alumno',
  path: '/alumno',
  getParentRoute: () => AppRoute,
} as any)
const AppAsociadoRoute = AppAsociadoRouteImport.update({
  id: '/asociado',
  path: '/asociado',
  getParentRoute: () => AppRoute,
} as any)
const AppCreadorRoute = AppCreadorRouteImport.update({
  id: '/creador',
  path: '/creador',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperiorRoute = AppSuperiorRouteImport.update({
  id: '/superior',
  path: '/superior',
  getParentRoute: () => AppRoute,
} as any)
const AppAlumnoIndexRoute = AppAlumnoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAlumnoRoute,
} as any)
const AppAlumnoAprendeRoute = AppAlumnoAprendeRouteImport.update({
  id: '/aprende',
  path: '/aprende',
  getParentRoute: () => AppAlumnoRoute,
} as any)
const AppAlumnoEscanerRoute = AppAlumnoEscanerRouteImport.update({
  id: '/escaner',
  path: '/escaner',
  getParentRoute: () => AppAlumnoRoute,
} as any)
const AppAlumnoMapaRoute = AppAlumnoMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AppAlumnoRoute,
} as any)
const AppAlumnoPremiosRoute = AppAlumnoPremiosRouteImport.update({
  id: '/premios',
  path: '/premios',
  getParentRoute: () => AppAlumnoRoute,
} as any)
const AppAlumnoRankingRoute = AppAlumnoRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppAlumnoRoute,
} as any)
const AppAlumnoViajeRoute = AppAlumnoViajeRouteImport.update({
  id: '/viaje',
  path: '/viaje',
  getParentRoute: () => AppAlumnoRoute,
} as any)
const AppAsociadoIndexRoute = AppAsociadoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAsociadoRoute,
} as any)
const AppAsociadoEscuelasRoute = AppAsociadoEscuelasRouteImport.update({
  id: '/escuelas',
  path: '/escuelas',
  getParentRoute: () => AppAsociadoRoute,
} as any)
const AppAsociadoLogisticaRoute = AppAsociadoLogisticaRouteImport.update({
  id: '/logistica',
  path: '/logistica',
  getParentRoute: () => AppAsociadoRoute,
} as any)
const AppCreadorIndexRoute = AppCreadorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCreadorRoute,
} as any)
const AppCreadorCircuitoRoute = AppCreadorCircuitoRouteImport.update({
  id: '/circuito',
  path: '/circuito',
  getParentRoute: () => AppCreadorRoute,
} as any)
const AppCreadorEducacionRoute = AppCreadorEducacionRouteImport.update({
  id: '/educacion',
  path: '/educacion',
  getParentRoute: () => AppCreadorRoute,
} as any)
const AppCreadorPremiosRoute = AppCreadorPremiosRouteImport.update({
  id: '/premios',
  path: '/premios',
  getParentRoute: () => AppCreadorRoute,
} as any)
const AppCreadorRankingRoute = AppCreadorRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppCreadorRoute,
} as any)
const AppSuperiorIndexRoute = AppSuperiorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSuperiorRoute,
} as any)
const AppSuperiorConfigRoute = AppSuperiorConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppSuperiorRoute,
} as any)
const AppSuperiorModulosRoute = AppSuperiorModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => AppSuperiorRoute,
} as any)
const AppSuperiorUsuariosRoute = AppSuperiorUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppSuperiorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alumno': typeof AppAlumnoRouteWithChildren
  '/asociado': typeof AppAsociadoRouteWithChildren
  '/creador': typeof AppCreadorRouteWithChildren
  '/superior': typeof AppSuperiorRouteWithChildren
  '/alumno/aprende': typeof AppAlumnoAprendeRoute
  '/alumno/escaner': typeof AppAlumnoEscanerRoute
  '/alumno/mapa': typeof AppAlumnoMapaRoute
  '/alumno/premios': typeof AppAlumnoPremiosRoute
  '/alumno/ranking': typeof AppAlumnoRankingRoute
  '/alumno/viaje': typeof AppAlumnoViajeRoute
  '/asociado/escuelas': typeof AppAsociadoEscuelasRoute
  '/asociado/logistica': typeof AppAsociadoLogisticaRoute
  '/creador/circuito': typeof AppCreadorCircuitoRoute
  '/creador/educacion': typeof AppCreadorEducacionRoute
  '/creador/premios': typeof AppCreadorPremiosRoute
  '/creador/ranking': typeof AppCreadorRankingRoute
  '/superior/config': typeof AppSuperiorConfigRoute
  '/superior/modulos': typeof AppSuperiorModulosRoute
  '/superior/usuarios': typeof AppSuperiorUsuariosRoute
  '/alumno/': typeof AppAlumnoIndexRoute
  '/asociado/': typeof AppAsociadoIndexRoute
  '/creador/': typeof AppCreadorIndexRoute
  '/superior/': typeof AppSuperiorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alumno/aprende': typeof AppAlumnoAprendeRoute
  '/alumno/escaner': typeof AppAlumnoEscanerRoute
  '/alumno/mapa': typeof AppAlumnoMapaRoute
  '/alumno/premios': typeof AppAlumnoPremiosRoute
  '/alumno/ranking': typeof AppAlumnoRankingRoute
  '/alumno/viaje': typeof AppAlumnoViajeRoute
  '/asociado/escuelas': typeof AppAsociadoEscuelasRoute
  '/asociado/logistica': typeof AppAsociadoLogisticaRoute
  '/creador/circuito': typeof AppCreadorCircuitoRoute
  '/creador/educacion': typeof AppCreadorEducacionRoute
  '/creador/premios': typeof AppCreadorPremiosRoute
  '/creador/ranking': typeof AppCreadorRankingRoute
  '/superior/config': typeof AppSuperiorConfigRoute
  '/superior/modulos': typeof AppSuperiorModulosRoute
  '/superior/usuarios': typeof AppSuperiorUsuariosRoute
  '/alumno': typeof AppAlumnoIndexRoute
  '/asociado': typeof AppAsociadoIndexRoute
  '/creador': typeof AppCreadorIndexRoute
  '/superior': typeof AppSuperiorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/alumno': typeof AppAlumnoRouteWithChildren
  '/_app/asociado': typeof AppAsociadoRouteWithChildren
  '/_app/creador': typeof AppCreadorRouteWithChildren
  '/_app/superior': typeof AppSuperiorRouteWithChildren
  '/_app/alumno/aprende': typeof AppAlumnoAprendeRoute
  '/_app/alumno/escaner': typeof AppAlumnoEscanerRoute
  '/_app/alumno/mapa': typeof AppAlumnoMapaRoute
  '/_app/alumno/premios': typeof AppAlumnoPremiosRoute
  '/_app/alumno/ranking': typeof AppAlumnoRankingRoute
  '/_app/alumno/viaje': typeof AppAlumnoViajeRoute
  '/_app/asociado/escuelas': typeof AppAsociadoEscuelasRoute
  '/_app/asociado/logistica': typeof AppAsociadoLogisticaRoute
  '/_app/creador/circuito': typeof AppCreadorCircuitoRoute
  '/_app/creador/educacion': typeof AppCreadorEducacionRoute
  '/_app/creador/premios': typeof AppCreadorPremiosRoute
  '/_app/creador/ranking': typeof AppCreadorRankingRoute
  '/_app/superior/config': typeof AppSuperiorConfigRoute
  '/_app/superior/modulos': typeof AppSuperiorModulosRoute
  '/_app/superior/usuarios': typeof AppSuperiorUsuariosRoute
  '/_app/alumno/': typeof AppAlumnoIndexRoute
  '/_app/asociado/': typeof AppAsociadoIndexRoute
  '/_app/creador/': typeof AppCreadorIndexRoute
  '/_app/superior/': typeof AppSuperiorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alumno'
    | '/asociado'
    | '/creador'
    | '/superior'
    | '/alumno/aprende'
    | '/alumno/escaner'
    | '/alumno/mapa'
    | '/alumno/premios'
    | '/alumno/ranking'
    | '/alumno/viaje'
    | '/asociado/escuelas'
    | '/asociado/logistica'
    | '/creador/circuito'
    | '/creador/educacion'
    | '/creador/premios'
    | '/creador/ranking'
    | '/superior/config'
    | '/superior/modulos'
    | '/superior/usuarios'
    | '/alumno/'
    | '/asociado/'
    | '/creador/'
    | '/superior/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alumno/aprende'
    | '/alumno/escaner'
    | '/alumno/mapa'
    | '/alumno/premios'
    | '/alumno/ranking'
    | '/alumno/viaje'
    | '/asociado/escuelas'
    | '/asociado/logistica'
    | '/creador/circuito'
    | '/creador/educacion'
    | '/creador/premios'
    | '/creador/ranking'
    | '/superior/config'
    | '/superior/modulos'
    | '/superior/usuarios'
    | '/alumno'
    | '/asociado'
    | '/creador'
    | '/superior'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/alumno'
    | '/_app/asociado'
    | '/_app/creador'
    | '/_app/superior'
    | '/_app/alumno/aprende'
    | '/_app/alumno/escaner'
    | '/_app/alumno/mapa'
    | '/_app/alumno/premios'
    | '/_app/alumno/ranking'
    | '/_app/alumno/viaje'
    | '/_app/asociado/escuelas'
    | '/_app/asociado/logistica'
    | '/_app/creador/circuito'
    | '/_app/creador/educacion'
    | '/_app/creador/premios'
    | '/_app/creador/ranking'
    | '/_app/superior/config'
    | '/_app/superior/modulos'
    | '/_app/superior/usuarios'
    | '/_app/alumno/'
    | '/_app/asociado/'
    | '/_app/creador/'
    | '/_app/superior/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/alumno': {
      id: '/_app/alumno'
      path: '/alumno'
      fullPath: '/alumno'
      preLoaderRoute: typeof AppAlumnoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/asociado': {
      id: '/_app/asociado'
      path: '/asociado'
      fullPath: '/asociado'
      preLoaderRoute: typeof AppAsociadoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/creador': {
      id: '/_app/creador'
      path: '/creador'
      fullPath: '/creador'
      preLoaderRoute: typeof AppCreadorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/superior': {
      id: '/_app/superior'
      path: '/superior'
      fullPath: '/superior'
      preLoaderRoute: typeof AppSuperiorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alumno/': {
      id: '/_app/alumno/'
      path: '/'
      fullPath: '/alumno/'
      preLoaderRoute: typeof AppAlumnoIndexRouteImport
      parentRoute: typeof AppAlumnoRoute
    }
    '/_app/alumno/aprende': {
      id: '/_app/alumno/aprende'
      path: '/aprende'
      fullPath: '/alumno/aprende'
      preLoaderRoute: typeof AppAlumnoAprendeRouteImport
      parentRoute: typeof AppAlumnoRoute
    }
    '/_app/alumno/escaner': {
      id: '/_app/alumno/escaner'
      path: '/escaner'
      fullPath: '/alumno/escaner'
      preLoaderRoute: typeof AppAlumnoEscanerRouteImport
      parentRoute: typeof AppAlumnoRoute
    }
    '/_app/alumno/mapa': {
      id: '/_app/alumno/mapa'
      path: '/mapa'
      fullPath: '/alumno/mapa'
      preLoaderRoute: typeof AppAlumnoMapaRouteImport
      parentRoute: typeof AppAlumnoRoute
    }
    '/_app/alumno/premios': {
      id: '/_app/alumno/premios'
      path: '/premios'
      fullPath: '/alumno/premios'
      preLoaderRoute: typeof AppAlumnoPremiosRouteImport
      parentRoute: typeof AppAlumnoRoute
    }
    '/_app/alumno/ranking': {
      id: '/_app/alumno/ranking'
      path: '/ranking'
      fullPath: '/alumno/ranking'
      preLoaderRoute: typeof AppAlumnoRankingRouteImport
      parentRoute: typeof AppAlumnoRoute
    }
    '/_app/alumno/viaje': {
      id: '/_app/alumno/viaje'
      path: '/viaje'
      fullPath: '/alumno/viaje'
      preLoaderRoute: typeof AppAlumnoViajeRouteImport
      parentRoute: typeof AppAlumnoRoute
    }
    '/_app/asociado/': {
      id: '/_app/asociado/'
      path: '/'
      fullPath: '/asociado/'
      preLoaderRoute: typeof AppAsociadoIndexRouteImport
      parentRoute: typeof AppAsociadoRoute
    }
    '/_app/asociado/escuelas': {
      id: '/_app/asociado/escuelas'
      path: '/escuelas'
      fullPath: '/asociado/escuelas'
      preLoaderRoute: typeof AppAsociadoEscuelasRouteImport
      parentRoute: typeof AppAsociadoRoute
    }
    '/_app/asociado/logistica': {
      id: '/_app/asociado/logistica'
      path: '/logistica'
      fullPath: '/asociado/logistica'
      preLoaderRoute: typeof AppAsociadoLogisticaRouteImport
      parentRoute: typeof AppAsociadoRoute
    }
    '/_app/creador/': {
      id: '/_app/creador/'
      path: '/'
      fullPath: '/creador/'
      preLoaderRoute: typeof AppCreadorIndexRouteImport
      parentRoute: typeof AppCreadorRoute
    }
    '/_app/creador/circuito': {
      id: '/_app/creador/circuito'
      path: '/circuito'
      fullPath: '/creador/circuito'
      preLoaderRoute: typeof AppCreadorCircuitoRouteImport
      parentRoute: typeof AppCreadorRoute
    }
    '/_app/creador/educacion': {
      id: '/_app/creador/educacion'
      path: '/educacion'
      fullPath: '/creador/educacion'
      preLoaderRoute: typeof AppCreadorEducacionRouteImport
      parentRoute: typeof AppCreadorRoute
    }
    '/_app/creador/premios': {
      id: '/_app/creador/premios'
      path: '/premios'
      fullPath: '/creador/premios'
      preLoaderRoute: typeof AppCreadorPremiosRouteImport
      parentRoute: typeof AppCreadorRoute
    }
    '/_app/creador/ranking': {
      id: '/_app/creador/ranking'
      path: '/ranking'
      fullPath: '/creador/ranking'
      preLoaderRoute: typeof AppCreadorRankingRouteImport
      parentRoute: typeof AppCreadorRoute
    }
    '/_app/superior/': {
      id: '/_app/superior/'
      path: '/'
      fullPath: '/superior/'
      preLoaderRoute: typeof AppSuperiorIndexRouteImport
      parentRoute: typeof AppSuperiorRoute
    }
    '/_app/superior/config': {
      id: '/_app/superior/config'
      path: '/config'
      fullPath: '/superior/config'
      preLoaderRoute: typeof AppSuperiorConfigRouteImport
      parentRoute: typeof AppSuperiorRoute
    }
    '/_app/superior/modulos': {
      id: '/_app/superior/modulos'
      path: '/modulos'
      fullPath: '/superior/modulos'
      preLoaderRoute: typeof AppSuperiorModulosRouteImport
      parentRoute: typeof AppSuperiorRoute
    }
    '/_app/superior/usuarios': {
      id: '/_app/superior/usuarios'
      path: '/usuarios'
      fullPath: '/superior/usuarios'
      preLoaderRoute: typeof AppSuperiorUsuariosRouteImport
      parentRoute: typeof AppSuperiorRoute
    }
  }
}

interface AppAlumnoRouteChildren {
  AppAlumnoAprendeRoute: typeof AppAlumnoAprendeRoute
  AppAlumnoEscanerRoute: typeof AppAlumnoEscanerRoute
  AppAlumnoMapaRoute: typeof AppAlumnoMapaRoute
  AppAlumnoPremiosRoute: typeof AppAlumnoPremiosRoute
  AppAlumnoRankingRoute: typeof AppAlumnoRankingRoute
  AppAlumnoViajeRoute: typeof AppAlumnoViajeRoute
  AppAlumnoIndexRoute: typeof AppAlumnoIndexRoute
}

const AppAlumnoRouteChildren: AppAlumnoRouteChildren = {
  AppAlumnoAprendeRoute: AppAlumnoAprendeRoute,
  AppAlumnoEscanerRoute: AppAlumnoEscanerRoute,
  AppAlumnoMapaRoute: AppAlumnoMapaRoute,
  AppAlumnoPremiosRoute: AppAlumnoPremiosRoute,
  AppAlumnoRankingRoute: AppAlumnoRankingRoute,
  AppAlumnoViajeRoute: AppAlumnoViajeRoute,
  AppAlumnoIndexRoute: AppAlumnoIndexRoute,
}

const AppAlumnoRouteWithChildren = AppAlumnoRoute._addFileChildren(
  AppAlumnoRouteChildren,
)

interface AppAsociadoRouteChildren {
  AppAsociadoEscuelasRoute: typeof AppAsociadoEscuelasRoute
  AppAsociadoLogisticaRoute: typeof AppAsociadoLogisticaRoute
  AppAsociadoIndexRoute: typeof AppAsociadoIndexRoute
}

const AppAsociadoRouteChildren: AppAsociadoRouteChildren = {
  AppAsociadoEscuelasRoute: AppAsociadoEscuelasRoute,
  AppAsociadoLogisticaRoute: AppAsociadoLogisticaRoute,
  AppAsociadoIndexRoute: AppAsociadoIndexRoute,
}

const AppAsociadoRouteWithChildren = AppAsociadoRoute._addFileChildren(
  AppAsociadoRouteChildren,
)

interface AppCreadorRouteChildren {
  AppCreadorCircuitoRoute: typeof AppCreadorCircuitoRoute
  AppCreadorEducacionRoute: typeof AppCreadorEducacionRoute
  AppCreadorPremiosRoute: typeof AppCreadorPremiosRoute
  AppCreadorRankingRoute: typeof AppCreadorRankingRoute
  AppCreadorIndexRoute: typeof AppCreadorIndexRoute
}

const AppCreadorRouteChildren: AppCreadorRouteChildren = {
  AppCreadorCircuitoRoute: AppCreadorCircuitoRoute,
  AppCreadorEducacionRoute: AppCreadorEducacionRoute,
  AppCreadorPremiosRoute: AppCreadorPremiosRoute,
  AppCreadorRankingRoute: AppCreadorRankingRoute,
  AppCreadorIndexRoute: AppCreadorIndexRoute,
}

const AppCreadorRouteWithChildren = AppCreadorRoute._addFileChildren(
  AppCreadorRouteChildren,
)

interface AppSuperiorRouteChildren {
  AppSuperiorConfigRoute: typeof AppSuperiorConfigRoute
  AppSuperiorModulosRoute: typeof AppSuperiorModulosRoute
  AppSuperiorUsuariosRoute: typeof AppSuperiorUsuariosRoute
  AppSuperiorIndexRoute: typeof AppSuperiorIndexRoute
}

const AppSuperiorRouteChildren: AppSuperiorRouteChildren = {
  AppSuperiorConfigRoute: AppSuperiorConfigRoute,
  AppSuperiorModulosRoute: AppSuperiorModulosRoute,
  AppSuperiorUsuariosRoute: AppSuperiorUsuariosRoute,
  AppSuperiorIndexRoute: AppSuperiorIndexRoute,
}

const AppSuperiorRouteWithChildren = AppSuperiorRoute._addFileChildren(
  AppSuperiorRouteChildren,
)

interface AppRouteChildren {
  AppAlumnoRoute: typeof AppAlumnoRouteWithChildren
  AppAsociadoRoute: typeof AppAsociadoRouteWithChildren
  AppCreadorRoute: typeof AppCreadorRouteWithChildren
  AppSuperiorRoute: typeof AppSuperiorRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAlumnoRoute: AppAlumnoRouteWithChildren,
  AppAsociadoRoute: AppAsociadoRouteWithChildren,
  AppCreadorRoute: AppCreadorRouteWithChildren,
  AppSuperiorRoute: AppSuperiorRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
